Repository Forme-SoftSquare/Project-S, pull requests merged in 2023-08, with the labels that each got.

#1 feat: add sprites & player shape class
  Assets/Scripts.meta
  Assets/Scripts/PlayerShape.meta
  Assets/Scripts/PlayerShape/Circle.cs
  Assets/Scripts/PlayerShape/Circle.cs.meta
  Assets/Scripts/PlayerShape/Hexagon.cs
  Assets/Scripts/PlayerShape/Hexagon.cs.meta
  Assets/Scripts/PlayerShape/Pentagon.cs
  Assets/Scripts/PlayerShape/Pentagon.cs.meta
  Assets/Scripts/PlayerShape/PlayerShape.cs
  Assets/Scripts/PlayerShape/PlayerShape.cs.meta
  Assets/Scripts/PlayerShape/Square.cs
  Assets/Scripts/PlayerShape/Square.cs.meta
  Assets/Scripts/PlayerShape/Triangle.cs
  Assets/Scripts/PlayerShape/Triangle.cs.meta
  Assets/Sprites.meta
  Assets/Sprites/Circle.png
  Assets/Sprites/Circle.png.meta
  Assets/Sprites/Hexagon.png
  Assets/Sprites/Hexagon.png.meta
  Assets/Sprites/Pentagon.png
  Assets/Sprites/Pentagon.png.meta
  Assets/Sprites/Square.png
  Assets/Sprites/Square.png.meta
  Assets/Sprites/Triangle.png
  Assets/Sprites/Triangle.png.meta
Labels: feature

#5 feat: camera follow
  Assets/Scenes/Main.unity
  Assets/Scenes/Main.unity.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
Labels: feature

#7 feat: Double jump & Dash & Variable jump height
  Assets/Scenes/Main.unity
  Assets/Scripts/PlayerCollision.cs
  Assets/Scripts/PlayerInput.cs
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/PlayerShape.cs
  Assets/Scripts/Shapes/Circle.cs
  Assets/Scripts/Shapes/Hexagon.cs
  Assets/Scripts/Shapes/Pentagon.cs
  Assets/Scripts/Shapes/Shape.cs
  Assets/Scripts/Shapes/Square.cs
  Assets/Scripts/Shapes/Triangle.cs
  Assets/Sprites/Shapes/Triangle.png.meta
Labels: feature

#9 fix: remove unused shapes
  Assets/Resources/Sprites/Shapes/Triangle.png.meta
  Assets/Sprites.meta
  Assets/Sprites/Shapes.meta
  Assets/Sprites/Shapes/Circle.png
  Assets/Sprites/Shapes/Circle.png.meta
  Assets/Sprites/Shapes/Hexagon.png
  Assets/Sprites/Shapes/Hexagon.png.meta
  Assets/Sprites/Shapes/Pentagon.png
  Assets/Sprites/Shapes/Pentagon.png.meta
  Assets/Sprites/Shapes/Square.png
  Assets/Sprites/Shapes/Square.png.meta
  Assets/Sprites/Shapes/Triangle.png
  Assets/Sprites/Shapes/Triangle.png.meta
Labels: improvement

#11 refactor: add player passive script & import player scripts & add walls
  Assets/Scenes/Main.unity
  Assets/Scripts/PlayerCollision.cs
  Assets/Scripts/PlayerController.cs
  Assets/Scripts/PlayerInput.cs
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/PlayerPassiveSkills.cs
  Assets/Scripts/PlayerPassiveSkills.cs.meta
  Assets/Scripts/PlayerShape.cs
  Assets/Scripts/Shapes/Triangle.cs
  ProjectSettings/TagManager.asset
Labels: improvement

#12 refactor: opti movement script & move passive skills in shape classes
  Assets/Scenes/Main.unity
  Assets/Scripts/PlayerCollision.cs
  Assets/Scripts/PlayerController.cs
  Assets/Scripts/PlayerInput.cs
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/PlayerPassiveSkills.cs
  Assets/Scripts/PlayerPassiveSkills.cs.meta
  Assets/Scripts/PlayerShape.cs
  Assets/Scripts/Shapes/Circle.cs
  Assets/Scripts/Shapes/Hexagon.cs
  Assets/Scripts/Shapes/Pentagon.cs
  Assets/Scripts/Shapes/Shape.cs
  Assets/Scripts/Shapes/Square.cs
  Assets/Scripts/Shapes/Triangle.cs
Labels: improvement

#13 Adding visual indications
  Assets/Scenes/Main.unity
  Assets/Scripts/PlayerController.cs
  Assets/Scripts/PlayerShape.cs
  Assets/Scripts/PlayerShape.cs.meta
  Assets/Scripts/Shapes/Triangle.cs
  ProjectSettings/TagManager.asset
Labels: feature

#14 Fix dash
  Assets/Scripts/PlayerInput.cs
  Assets/Scripts/Shapes/Triangle.cs
Labels: improvement

#16 feat: shape stats
  Assets/Scripts/PlayerMovement.cs
  Assets/Scripts/Shapes/Circle.cs
  Assets/Scripts/Shapes/Hexagon.cs
  Assets/Scripts/Shapes/Pentagon.cs
  Assets/Scripts/Shapes/Shape.cs
  Assets/Scripts/Shapes/ShapeStats.cs
  Assets/Scripts/Shapes/ShapeStats.cs.meta
  Assets/Scripts/Shapes/Square.cs
  Assets/Scripts/Shapes/Triangle.cs
Labels: feature, player
